import { scheduleView } from "./schedule-view.js";
import { issueList } from "./issue-list.js";
import { tutorView } from "./tutor-view.js";

export function renderApp({ tutors, lessons, issues, filterTutor, date, selectedId, message, conflictsOnly, focusConflictIds }) {
  const conflictIds = new Set(issues.flatMap((issue) => [issue.lessonId, issue.relatedLessonId]));
  const unresolvedIssues = issues.filter((issue) => !issue.resolved);
  const unresolvedConflictIds = new Set(unresolvedIssues.flatMap((issue) => [issue.lessonId, issue.relatedLessonId]));
  const shown = [...lessons].filter((lesson) => (!filterTutor || lesson.tutorId === filterTutor) && (!date || lesson.date === date) && (!conflictsOnly || conflictIds.has(lesson.id)) && (!focusConflictIds.length || focusConflictIds.includes(lesson.id))).sort((a, b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  return `<section class="shell"><header><div><p class="eyebrow">CENTRE · COORDINATION</p><h1>Teacher schedule</h1><p class="lede">One current schedule, with conflict checks before every change.</p></div><button id="new-lesson" class="primary">+ Add lesson</button></header><section class="toolbar"><label class="field">Date<input id="date-filter" type="date" value="${date || ""}"></label>${tutorView(tutors, filterTutor)}<button id="conflicts-filter" class="secondary ${conflictsOnly ? "active-filter" : ""}" aria-pressed="${conflictsOnly}">Conflicts only (${issues.length})</button><button id="clear-filter" class="secondary">Show all</button><button id="export-csv" class="link-button export-button">Export CSV</button></section>${message ? `<p class="message">${message}</p>` : ""}<div class="grid"><section class="panel schedule"><div class="panel-title"><h2>Current schedule</h2><span>${shown.length} lessons${focusConflictIds.length ? " · focused conflict" : ""}</span></div>${scheduleView(shown, tutors, selectedId, unresolvedConflictIds)}</section><aside class="panel"><div class="panel-title"><h2>Schedule checks</h2><span>${unresolvedIssues.length} open · ${issues.length} policy conflicts</span></div>${issueList(unresolvedIssues)}</aside></div><section id="editor" class="panel editor hidden"></section><p class="footnote">Source data is loaded from CSV. API mode saves changes back to the CSV file.</p></section>`;
}

export function editorView(lesson, tutors) {
  const l = lesson || { id: "", tutorId: tutors[0]?.id || "", date: "", startTime: "09:00", durationMin: 60, metadata: { student: "", room: "", status: "booked", note: "" } };
  return `<div class="panel-title"><h2>${lesson ? `Update ${l.id}` : "Add lesson"}</h2><button id="close-editor" class="link-button">Close</button></div><form id="lesson-form" class="form" data-new="${lesson ? "false" : "true"}"><label class="field">Lesson ID<input name="id" value="${l.id}" ${lesson ? "readonly" : "required"}></label><label class="field">Student<input name="student" value="${l.metadata.student || ""}" required></label><label class="field">Tutor<select name="tutorId">${tutors.map((t) => `<option value="${t.id}" ${t.id === l.tutorId ? "selected" : ""}>${t.name}</option>`).join("")}</select></label><label class="field">Date<input name="date" type="date" value="${l.date}" required></label><label class="field">Start time<input name="startTime" type="time" value="${l.startTime}" required></label><label class="field">Duration (minutes)<input name="durationMin" type="number" min="1" value="${l.durationMin}" required></label><label class="field">Room<input name="room" value="${l.metadata.room || ""}"></label><label class="field">Status<select name="status">${["booked", "cancelled", "no_show"].map((s) => `<option ${s === l.metadata.status ? "selected" : ""}>${s}</option>`).join("")}</select></label><label class="field full">Note<input name="note" value="${l.metadata.note || ""}"></label><div class="form-actions"><button class="primary" type="submit">Validate and save</button></div></form>`;
}
