import { CsvScheduleAdapter } from "./adapters/csv-schedule-adapter.js";
import { ApiScheduleAdapter } from "./adapters/api-schedule-adapter.js";
import { loadSchedule } from "./application/load-schedule.js";
import { validateSchedule } from "./application/validate-schedule.js";
import { saveLesson } from "./domain/schedule-service.js";
import { editorView, renderApp } from "./ui/app.js";
import { config } from "./config/app-config.js";

const root = document.querySelector("#app");
const state = { tutors: [], lessons: [], issues: [], filterTutor: "", date: "", selectedId: "", message: "", conflictsOnly: false, focusConflictIds: [] };
let repository;

function render() { state.issues = validateSchedule(state.lessons); root.innerHTML = renderApp(state); bind(); }
function csvValue(value) { const text = String(value ?? ""); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
const toSnake = (key) => key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
function exportCsv() { const core = ["lesson_id", "tutor_id", "date", "start_time", "duration_min"]; const rows = state.lessons.map((lesson) => ({ lesson_id: lesson.id, tutor_id: lesson.tutorId, date: lesson.date, start_time: lesson.startTime, duration_min: lesson.durationMin, ...Object.fromEntries(Object.entries(lesson.metadata).filter(([key]) => !["changeHistory", "updatedAt"].includes(key)).map(([key, value]) => [toSnake(key), value === true ? "true" : value === false ? "false" : value ?? ""])) })); const fields = [...core, ...new Set(rows.flatMap((row) => Object.keys(row)).filter((field) => !core.includes(field)))]; const csv = `\uFEFF${[fields.join(","), ...rows.map((row) => fields.map((field) => csvValue(row[field])).join(","))].join("\n")}\n`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = "lessons_export.csv"; link.click(); URL.revokeObjectURL(link.href); }
function openEditor(id) { const target = document.querySelector("#editor"); target.classList.remove("hidden"); target.innerHTML = editorView(state.lessons.find((l) => l.id === id), state.tutors); bindEditor(); target.scrollIntoView({ behavior: "smooth", block: "nearest" }); }
function bindEditor() { document.querySelector("#close-editor")?.addEventListener("click", () => document.querySelector("#editor").classList.add("hidden")); document.querySelector("#lesson-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const f = new FormData(event.currentTarget); const isNew = event.currentTarget.dataset.new === "true"; const current = state.lessons.find((lesson) => lesson.id === f.get("id").trim()); const draft = { id: f.get("id").trim(), tutorId: f.get("tutorId"), date: f.get("date"), startTime: f.get("startTime"), durationMin: Number(f.get("durationMin")), metadata: { student: f.get("student").trim(), room: f.get("room").trim(), status: f.get("status"), note: f.get("note").trim(), cancelledAt: null, conflictResolved: current?.metadata.conflictResolved ?? null, changeHistory: [] } }; if (isNew && state.lessons.some((l) => l.id === draft.id)) { state.message = `Could not save: lesson ID ${draft.id} already exists.`; render(); openEditor(); return; } const result = saveLesson(state.lessons, draft); try { if (config.dataSource === "api") { const saved = await repository.save(result.lessons.find((l) => l.id === draft.id), isNew); state.lessons = isNew ? [...state.lessons, saved] : state.lessons.map((l) => l.id === saved.id ? saved : l); } else { state.lessons = result.lessons; } state.selectedId = draft.id; state.message = config.dataSource === "api" ? "Saved to the CSV file." : "Schedule updated for this session."; render(); document.querySelector("#editor").classList.add("hidden"); } catch (error) { state.message = `Could not save: ${error.message}`; render(); openEditor(draft.id); } }); }
async function approveConflict(ids) { const targets = ids.split(",").map((id) => state.lessons.find((item) => item.id === id)).filter(Boolean).map((lesson) => ({ ...lesson, metadata: { ...lesson.metadata, conflictResolved: true } })); try { const saved = []; for (const lesson of targets) saved.push(config.dataSource === "api" ? await repository.save(lesson, false) : lesson); state.lessons = state.lessons.map((item) => saved.find((lesson) => lesson.id === item.id) || item); state.message = "Exception approved. The policy conflict remains available in Conflicts only."; render(); } catch (error) { state.message = `Could not approve exception: ${error.message}`; render(); } }
function bind() { document.querySelector("#tutor-filter")?.addEventListener("change", (e) => { state.filterTutor = e.target.value; state.focusConflictIds = []; render(); }); document.querySelector("#date-filter")?.addEventListener("change", (e) => { state.date = e.target.value; state.focusConflictIds = []; render(); }); document.querySelector("#conflicts-filter")?.addEventListener("click", () => { state.conflictsOnly = !state.conflictsOnly; state.focusConflictIds = []; render(); }); document.querySelector("#clear-filter")?.addEventListener("click", () => { state.filterTutor = ""; state.date = ""; state.conflictsOnly = false; state.focusConflictIds = []; render(); }); document.querySelector("#export-csv")?.addEventListener("click", exportCsv); document.querySelector("#new-lesson")?.addEventListener("click", () => openEditor()); document.querySelectorAll("[data-edit]").forEach((button) => button.addEventListener("click", () => { state.selectedId = button.dataset.edit; render(); openEditor(state.selectedId); })); document.querySelectorAll("[data-focus-conflict]").forEach((button) => button.addEventListener("click", () => { state.focusConflictIds = button.dataset.focusConflict.split(","); state.conflictsOnly = false; render(); })); document.querySelectorAll("[data-approve-conflict]").forEach((button) => button.addEventListener("click", () => approveConflict(button.dataset.approveConflict))); }

try {
  repository = config.dataSource === "csv" ? new CsvScheduleAdapter() : config.dataSource === "api" ? new ApiScheduleAdapter() : null;
  if (!repository) throw new Error(`Data source \"${config.dataSource}\" is configured but its adapter is not implemented yet.`);
  Object.assign(state, await loadSchedule(repository));
  document.title = config.app.name;
  render();
  if (config.features.pwa && "serviceWorker" in navigator) navigator.serviceWorker.register("./public/service-worker.js");
} catch (error) { root.innerHTML = `<section class="shell"><h1>Could not load the schedule</h1><p>${error.message}</p></section>`; }
